server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  datasource: 
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3308/security1?characterEncoding=UTF-8
    username: cos
    password: cos1234

  output:
    ansi:
      enabled: always

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect    
    hibernate:
      ddl-auto: create #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true	

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 173710330781-vcj931s3hgt8fprkup82govlhaa10iip.apps.googleusercontent.com
            client-secret: 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 
            scope:
            - email
            - profile
          facebook:
            client-id: 105100109305709
            client-secret: 292c039ba1e83a34b730b7ecbd44e194
            scope:
            - email
            - public_profile     

             
logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      SQL: DEBUG
      '[com.cos.security]': DEBUG

